- name: Run nginx
  hosts: machines
  become: yes
  vars:
    root: website
    config_name: nginx.conf.j2
    website_name: sber.php

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

  tasks:

  # Напиши плейбук в ansible, который установит и настроит nginx 
  - name: Install nginx and php
    apt:
      name:
        - nginx
        - php8.1-fpm
      state: latest
      update_cache: yes

  - name: Start php service
    service:
      name: php8.1-fpm
      state: started

  - name: Copy new website to server
    copy:
      src: "{{ root }}/{{ website_name }}"
      dest: /var/www/html/{{ website_name }}

  # Плейбук должен при изменении конфига nginx подкладывать и давать команду на перечитку конфига
  - name: Update nginx config
    template:
      src: "{{ root }}/{{ config_name }}"
      dest: /etc/nginx/sites-available/default
    notify: Restart nginx # Перечитка конфига (просто перезагрузка сервера) при замене файла (changed=true)

  - name: Enable new site
    file:
      src: /etc/nginx/sites-available/default
      dest: /etc/nginx/sites-enabled/default
      state: link
